output : client_udp.c server_udp.c client_broken_ftp.c server_broken_ftp.c
	gcc -o client_udp.exe client_udp.c
	gcc -o server_udp.exe server_udp.c
	gcc -o client_broken_ftp.exe client_broken_ftp.c 
	gcc -o server_broken_ftp.exe server_broken_ftp.c